//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public Check()
        {
            this.Purchase = new HashSet<Purchase>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public decimal Summ { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> NeighborId { get; set; }
    
        public virtual Neighbor Neighbor { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<Purchase> Purchase { get; set; }
    }
}
