//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int Id { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public Nullable<int> NeighborId { get; set; }
        public decimal CurrencyPrice { get; set; }
    
        public virtual Neighbor Neighbor { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
