//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class n_Checks
    {
        public n_Checks()
        {
            this.n_Purchases = new HashSet<n_Purchases>();
        }
    
        public int Id { get; set; }
        public int NeighbourId { get; set; }
        public int StoreId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual n_Neighbours n_Neighbours { get; set; }
        public virtual n_Stores n_Stores { get; set; }
        public virtual ICollection<n_Purchases> n_Purchases { get; set; }
    }
}
