//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class n_Products
    {
        public n_Products()
        {
            this.n_Price = new HashSet<n_Price>();
            this.n_Purchases = new HashSet<n_Purchases>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<n_Price> n_Price { get; set; }
        public virtual ICollection<n_Purchases> n_Purchases { get; set; }
    }
}
