//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class n_Purchases
    {
        public n_Purchases()
        {
            this.n_WhoWillUse = new HashSet<n_WhoWillUse>();
        }
    
        public int Id { get; set; }
        public int CheckId { get; set; }
        public int ProductId { get; set; }
        public decimal Cost { get; set; }
        public decimal CostPerPerson { get; set; }
    
        public virtual n_Checks n_Checks { get; set; }
        public virtual n_Products n_Products { get; set; }
        public virtual ICollection<n_WhoWillUse> n_WhoWillUse { get; set; }
    }
}
