//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class n_Stores
    {
        public n_Stores()
        {
            this.n_Checks = new HashSet<n_Checks>();
            this.n_Price = new HashSet<n_Price>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<n_Checks> n_Checks { get; set; }
        public virtual ICollection<n_Price> n_Price { get; set; }
    }
}
