//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class n_Transactions
    {
        public int Id { get; set; }
        public int FromNeighbourId { get; set; }
        public int ToNeighbourId { get; set; }
        public decimal Summa { get; set; }
        public string Caption { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDebitOff { get; set; }
    
        public virtual n_Neighbours n_FromNeighbours { get; set; }
        public virtual n_Neighbours n_ToNeighbours { get; set; }
    }
}
