//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neighbor
    {
        public Neighbor()
        {
            this.Check = new HashSet<Check>();
            this.Currency = new HashSet<Currency>();
            this.WhoWillUse = new HashSet<WhoWillUse>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Check> Check { get; set; }
        public virtual ICollection<Currency> Currency { get; set; }
        public virtual ICollection<WhoWillUse> WhoWillUse { get; set; }
    }
}
