//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neighbours
    {
        public Neighbours()
        {
            this.Checks = new HashSet<Checks>();
            this.WhoWillUse = new HashSet<WhoWillUse>();
            this.MyPaysNP = new HashSet<Transactions>();
            this.PaysForMeNP = new HashSet<Transactions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual ICollection<Checks> Checks { get; set; }
        public virtual ICollection<WhoWillUse> WhoWillUse { get; set; }
        public virtual ICollection<Transactions> MyPaysNP { get; set; }
        public virtual ICollection<Transactions> PaysForMeNP { get; set; }
    }
}
