//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uh357966_db2Entities1 : DbContext
    {
        public uh357966_db2Entities1()
            : base("name=uh357966_db2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<n_Checks> n_Checks { get; set; }
        public virtual DbSet<n_Neighbours> n_Neighbours { get; set; }
        public virtual DbSet<n_Price> n_Price { get; set; }
        public virtual DbSet<n_Products> n_Products { get; set; }
        public virtual DbSet<n_Purchases> n_Purchases { get; set; }
        public virtual DbSet<n_Stores> n_Stores { get; set; }
        public virtual DbSet<n_WhoWillUse> n_WhoWillUse { get; set; }
        public virtual DbSet<n_Transactions> n_Transactions { get; set; }
    }
}
