//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uh357966_db2Entities1 : DbContext
    {
        public uh357966_db2Entities1()
            : base("name=uh357966_db2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<n_Checks> n_Checks { get; set; }
        public virtual DbSet<n_Neighbours> n_Neighbours { get; set; }
        public virtual DbSet<n_Price> n_Price { get; set; }
        public virtual DbSet<n_Products> n_Products { get; set; }
        public virtual DbSet<n_Purchases> n_Purchases { get; set; }
        public virtual DbSet<n_Stores> n_Stores { get; set; }
        public virtual DbSet<n_WhoWillUse> n_WhoWillUse { get; set; }
    }
}
