//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Purchase()
        {
            this.Currency = new HashSet<Currency>();
            this.WhoWillUse = new HashSet<WhoWillUse>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public decimal Count { get; set; }
        public decimal Summa { get; set; }
        public Nullable<int> CheckId { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual ICollection<Currency> Currency { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<WhoWillUse> WhoWillUse { get; set; }
    }
}
