//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaverCore
{ 
    using System;
    using System.Collections.Generic;
    
    public partial class FixedPays
    {
        public int Id { get; set; }
        public decimal Price { get; set; }
        public int InvoiceId { get; set; }
        public int NameId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual FPName FPName { get; set; }
    }
}
