//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver
{
    using System;
    using System.Collections.Generic;
    
    public partial class GasTarif
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GasTarif()
        {
            this.Gas = new HashSet<Gas>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public int LevelRange { get; set; }
        public decimal LowPrice { get; set; }
        public Nullable<decimal> HighPrice { get; set; }
        public int StartMonth { get; set; }
        public int EndMonth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gas> Gas { get; set; }
    }
}
