//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.FixedPays = new HashSet<FixedPays>();
        }
    
        public int Id { get; set; }
        public int ColdWaterPriceId { get; set; }
        public Nullable<int> HotWaterPriceId { get; set; }
        public int ElectricityPriceId { get; set; }
        public Nullable<int> GasPriceId { get; set; }
        public int Month { get; set; }
        public System.DateTime CreationDate { get; set; }
        public decimal TotalSum { get; set; }
        public int Year { get; set; }
        public string Address { get; set; }
    
        public virtual Electricity Electricity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedPays> FixedPays { get; set; }
        public virtual Gas Gas { get; set; }
        public virtual Water HotWater { get; set; }
        public virtual Water ColdWater { get; set; }
    }
}
