//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaver
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stores
    {
        public Stores()
        {
            this.Checks = new HashSet<Checks>();
            this.Price = new HashSet<Price>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Photo { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Checks> Checks { get; set; }
        public virtual ICollection<Price> Price { get; set; }
    }
}
