//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckSaverCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Water
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Water()
        {
            this.HotInvoices = new HashSet<Invoice>();
            this.ColdInvoices = new HashSet<Invoice>();
        }
    
        public int Id { get; set; }
        public decimal StartValue { get; set; }
        public decimal FinishValue { get; set; }
        public decimal ValueDifference { get; set; }
        public int TarifId { get; set; }
        public decimal TotalCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> HotInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> ColdInvoices { get; set; }
        public virtual WaterTarif WaterTarif { get; set; }
    }
}
